# Generated by Django 5.2.17 on 2026-09-19 17:03

import apps.products.models
import apps.shared.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Өөрчилсөн огноо')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Устгагдсан эсэх')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Устгасан огноо')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Нийтийн дугаар (UUID)')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Нэр')),
                ('description', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('material', models.CharField(blank=True, max_length=255, verbose_name='Материалын мэдээлэл')),
                ('care_instructions', models.TextField(blank=True, verbose_name='Арчилгааны заавар')),
                ('size_chart_image', models.ImageField(blank=True, null=True, upload_to=apps.products.models.size_chart_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], code='invalid_image_extension', message='Зөвхөн JPG, JPEG, PNG, WEBP форматын зураг оруулна уу.'), apps.shared.validators.validate_image_size], verbose_name='Размерийн хүснэгт')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Үнэ (RRP)')),
                ('status', models.CharField(choices=[('DRAFT', 'Ноорог'), ('ACTIVE', 'Идэвхтэй'), ('INACTIVE', 'Идэвхгүй')], default='DRAFT', max_length=20, verbose_name='Төлөв')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Сүүлд өөрчилсөн хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Бараа',
                'verbose_name_plural': 'Бараа бүтээгдэхүүн',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Өөрчилсөн огноо')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Устгагдсан эсэх')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Устгасан огноо')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Нийтийн дугаар (UUID)')),
                ('image', models.ImageField(upload_to=apps.products.models.product_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], code='invalid_image_extension', message='Зөвхөн JPG, JPEG, PNG, WEBP форматын зураг оруулна уу.'), apps.shared.validators.validate_image_size], verbose_name='Зураг')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Үндсэн зураг эсэх')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Харагдах дараалал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Бараа')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Сүүлд өөрчилсөн хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Барааны зураг',
                'verbose_name_plural': 'Барааны зурагнууд',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Өөрчилсөн огноо')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Устгагдсан эсэх')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Устгасан огноо')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Нийтийн дугаар (UUID)')),
                ('color', models.CharField(choices=[('BLACK', 'Хар'), ('WHITE', 'Цагаан'), ('BEIGE', 'Бэйж'), ('GREEN', 'Ногоон'), ('PINK', 'Ягаан'), ('RED', 'Улаан')], max_length=20, verbose_name='Өнгө')),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL')], max_length=10, verbose_name='Размер')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Үлдэгдэл')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Бараа')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Сүүлд өөрчилсөн хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Барааны хувилбар',
                'verbose_name_plural': 'Барааны хувилбарууд',
                'ordering': ['product', 'color', 'size'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='unique_active_product_code'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('product', 'color', 'size'), name='unique_active_product_variant'),
        ),
    ]
