# Generated by Django 5.2.17 on 2026-09-19 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='quantity',
        ),
    ]
