# Generated by Django 5.2.17 on 2026-09-19 18:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_remove_productvariant_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Өөрчилсөн огноо')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Устгагдсан эсэх')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Устгасан огноо')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Нийтийн дугаар (UUID)')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Дугаар')),
                ('note', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Сүүлд өөрчилсөн хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Нэгдсэн захиалга',
                'verbose_name_plural': 'Нэгдсэн захиалгууд',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Өөрчилсөн огноо')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Устгагдсан эсэх')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Устгасан огноо')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Нийтийн дугаар (UUID)')),
                ('order_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Захиалгын дугаар')),
                ('status', models.CharField(choices=[('REQUESTED', 'Хүсэлт илгээсэн'), ('UNDER_REVIEW', 'Хянагдаж байгаа'), ('APPROVED', 'Батлагдсан'), ('REJECTED', 'Татгалзсан'), ('PAYMENT_PENDING', 'Төлбөр хүлээгдэж буй'), ('PAYMENT_REVIEW', 'Төлбөр шалгагдаж буй'), ('PAYMENT_CONFIRMED', 'Төлбөр баталгаажсан'), ('GROUPED_ORDER', 'Нэгдсэн захиалгад орсон'), ('ARRIVED', 'Ирсэн'), ('SHIPPING', 'Хүргэлтэд гарсан'), ('COMPLETED', 'Дууссан'), ('CANCELLED', 'Цуцлагдсан')], default='REQUESTED', max_length=30, verbose_name='Төлөв')),
                ('note', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('rejected_reason', models.CharField(blank=True, max_length=255, verbose_name='Татгалзсан шалтгаан')),
                ('cancelled_reason', models.CharField(blank=True, max_length=255, verbose_name='Цуцалсан шалтгаан')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('grouped_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.groupedorder', verbose_name='Нэгдсэн захиалга')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Захиалагч')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Сүүлд өөрчилсөн хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Захиалга',
                'verbose_name_plural': 'Захиалгууд',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Өөрчилсөн огноо')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Устгагдсан эсэх')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Устгасан огноо')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Нийтийн дугаар (UUID)')),
                ('quantity', models.PositiveIntegerField(verbose_name='Тоо ширхэг')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Нэгжийн үнэ')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Захиалга')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Сүүлд өөрчилсөн хэрэглэгч')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.productvariant', verbose_name='Барааны хувилбар')),
            ],
            options={
                'verbose_name': 'Захиалгын мөр',
                'verbose_name_plural': 'Захиалгын мөрүүд',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Өөрчилсөн огноо')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Устгагдсан эсэх')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Устгасан огноо')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Нийтийн дугаар (UUID)')),
                ('from_status', models.CharField(blank=True, choices=[('REQUESTED', 'Хүсэлт илгээсэн'), ('UNDER_REVIEW', 'Хянагдаж байгаа'), ('APPROVED', 'Батлагдсан'), ('REJECTED', 'Татгалзсан'), ('PAYMENT_PENDING', 'Төлбөр хүлээгдэж буй'), ('PAYMENT_REVIEW', 'Төлбөр шалгагдаж буй'), ('PAYMENT_CONFIRMED', 'Төлбөр баталгаажсан'), ('GROUPED_ORDER', 'Нэгдсэн захиалгад орсон'), ('ARRIVED', 'Ирсэн'), ('SHIPPING', 'Хүргэлтэд гарсан'), ('COMPLETED', 'Дууссан'), ('CANCELLED', 'Цуцлагдсан')], max_length=30, verbose_name='Өмнөх төлөв')),
                ('to_status', models.CharField(choices=[('REQUESTED', 'Хүсэлт илгээсэн'), ('UNDER_REVIEW', 'Хянагдаж байгаа'), ('APPROVED', 'Батлагдсан'), ('REJECTED', 'Татгалзсан'), ('PAYMENT_PENDING', 'Төлбөр хүлээгдэж буй'), ('PAYMENT_REVIEW', 'Төлбөр шалгагдаж буй'), ('PAYMENT_CONFIRMED', 'Төлбөр баталгаажсан'), ('GROUPED_ORDER', 'Нэгдсэн захиалгад орсон'), ('ARRIVED', 'Ирсэн'), ('SHIPPING', 'Хүргэлтэд гарсан'), ('COMPLETED', 'Дууссан'), ('CANCELLED', 'Цуцлагдсан')], max_length=30, verbose_name='Шинэ төлөв')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Шалтгаан')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Захиалга')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Сүүлд өөрчилсөн хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Захиалгын төлөвийн түүх',
                'verbose_name_plural': 'Захиалгын төлөвийн түүхүүд',
                'ordering': ['-created_at'],
            },
        ),
    ]
