# Generated by Django 5.2.17 on 2026-09-19 16:10

import apps.accounts.managers
import apps.shared.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Өөрчилсөн огноо')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Устгагдсан эсэх')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Устгасан огноо')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Нийтийн дугаар (UUID)')),
                ('phone_number', models.CharField(help_text='Нэвтрэх нэрээр ашиглагдана. 8 оронтой байна.', max_length=8, unique=True, validators=[apps.shared.validators.MongolianPhoneNumberValidator()], verbose_name='Утасны дугаар')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='И-мэйл хаяг')),
                ('last_name', models.CharField(max_length=150, verbose_name='Овог')),
                ('first_name', models.CharField(max_length=150, verbose_name='Нэр')),
                ('role', models.CharField(choices=[('ADMIN', 'Админ'), ('MAIN_SELLER', 'Үндсэн Борлуулагч'), ('CONTRACT_SELLER', 'Гэрээт Борлуулагч')], default='CONTRACT_SELLER', max_length=20, verbose_name='Хэрэглэгчийн төрөл')),
                ('store_name', models.CharField(blank=True, max_length=255, verbose_name='Дэлгүүрийн нэр')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Аймаг')),
                ('soum', models.CharField(blank=True, max_length=100, verbose_name='Сум')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Дүүрэг')),
                ('address', models.TextField(blank=True, verbose_name='Хаяг')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Банкны нэр')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Дансны дугаар')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Админ баталгаажуулсан эсэх')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Баталгаажуулсан огноо')),
                ('must_change_password', models.BooleanField(default=True, verbose_name='Нэвтрэхэд нууц үг заавал солих эсэх')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Django Admin-д нэвтрэх эрхтэй эсэх')),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL, verbose_name='Баталгаажуулсан админ')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('parent_seller', models.ForeignKey(blank=True, help_text='Гэрээт борлуулагч заавал энэ талбараар нэг үндсэн борлуулагчид харьяалагдана.', limit_choices_to={'role': 'MAIN_SELLER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_sellers', to=settings.AUTH_USER_MODEL, verbose_name='Харьяалагдах үндсэн борлуулагч')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Сүүлд өөрчилсөн хэрэглэгч')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Хэрэглэгч',
                'verbose_name_plural': 'Хэрэглэгчид',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
