# Generated by Django 5.2.17 on 2026-09-19 18:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_remove_productvariant_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Өөрчилсөн огноо')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Устгагдсан эсэх')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Устгасан огноо')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Нийтийн дугаар (UUID)')),
                ('original_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Анхны үнэ')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Тээврийн зардал')),
                ('packaging_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Савлагааны зардал')),
                ('transfer_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Шилжүүлгийн шимтгэл')),
                ('risk_reserve', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Эрсдэлийн нөөц')),
                ('marketing_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Маркетингийн зардал')),
                ('supplier_info', models.CharField(blank=True, max_length=255, verbose_name='Нийлүүлэгчийн мэдээлэл')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='products.product', verbose_name='Бараа')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Сүүлд өөрчилсөн хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Барааны өртөг',
                'verbose_name_plural': 'Барааны өртгүүд',
            },
        ),
        migrations.CreateModel(
            name='ProfitDistributionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Өөрчилсөн огноо')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Устгагдсан эсэх')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Устгасан огноо')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Нийтийн дугаар (UUID)')),
                ('owner_percentage', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, verbose_name='Эзний хувь (%)')),
                ('main_seller_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='Үндсэн Борлуулагчийн хувь (%)')),
                ('contract_seller_percentage', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, verbose_name='Гэрээт Борлуулагчийн хувь (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Сүүлд өөрчилсөн хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Ашиг хуваарилалтын тохиргоо',
                'verbose_name_plural': 'Ашиг хуваарилалтын тохиргоо',
                'ordering': ['-created_at'],
            },
        ),
    ]
