# Generated by Django 5.2.17 on 2026-09-19 18:14

import apps.payments.models
import apps.shared.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Өөрчилсөн огноо')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Устгагдсан эсэх')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Устгасан огноо')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Нийтийн дугаар (UUID)')),
                ('receipt_file', models.FileField(upload_to=apps.payments.models.receipt_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'pdf'], code='invalid_receipt_extension', message='Зөвхөн JPG, JPEG, PNG, WEBP, PDF файл оруулна уу.'), apps.shared.validators.validate_receipt_size], verbose_name='Төлбөрийн баримт')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Төлсөн дүн')),
                ('status', models.CharField(choices=[('PENDING', 'Шалгагдаж буй'), ('CONFIRMED', 'Баталгаажсан'), ('REJECTED', 'Татгалзсан')], default='PENDING', max_length=20, verbose_name='Төлөв')),
                ('rejected_reason', models.CharField(blank=True, max_length=255, verbose_name='Татгалзсан шалтгаан')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Баталгаажуулсан огноо')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='Захиалга')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Сүүлд өөрчилсөн хэрэглэгч')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL, verbose_name='Баталгаажуулсан админ')),
            ],
            options={
                'verbose_name': 'Төлбөр',
                'verbose_name_plural': 'Төлбөрүүд',
                'ordering': ['-created_at'],
            },
        ),
    ]
