# Generated by Django 5.2.17 on 2026-09-19 17:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_remove_productvariant_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Өөрчилсөн огноо')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Устгагдсан эсэх')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Устгасан огноо')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Нийтийн дугаар (UUID)')),
                ('movement_type', models.CharField(choices=[('STOCK_IN', 'Орлого'), ('STOCK_OUT', 'Зарлага'), ('RESERVATION', 'Нөөцлөлт'), ('RELEASE_RESERVATION', 'Нөөцлөлт цуцлах'), ('ADJUSTMENT', 'Тохируулга')], max_length=30, verbose_name='Хөдөлгөөний төрөл')),
                ('quantity_change', models.IntegerField(verbose_name='Өөрчлөлт (+/-)')),
                ('quantity_before', models.PositiveIntegerField(verbose_name='Өмнөх нийт үлдэгдэл')),
                ('quantity_after', models.PositiveIntegerField(verbose_name='Дараах нийт үлдэгдэл')),
                ('reserved_before', models.PositiveIntegerField(verbose_name='Өмнөх нөөцлөлт')),
                ('reserved_after', models.PositiveIntegerField(verbose_name='Дараах нөөцлөлт')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Шалтгаан')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Холбогдох баримт')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Сүүлд өөрчилсөн хэрэглэгч')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='products.productvariant', verbose_name='Барааны хувилбар')),
            ],
            options={
                'verbose_name': 'Агуулахын хөдөлгөөн',
                'verbose_name_plural': 'Агуулахын хөдөлгөөний түүх',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Өөрчилсөн огноо')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Устгагдсан эсэх')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Устгасан огноо')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Нийтийн дугаар (UUID)')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Нийт үлдэгдэл')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, verbose_name='Нөөцлөгдсөн хэмжээ')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Сүүлд өөрчилсөн хэрэглэгч')),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.productvariant', verbose_name='Барааны хувилбар')),
            ],
            options={
                'verbose_name': 'Үлдэгдэл',
                'verbose_name_plural': 'Агуулахын үлдэгдэл',
                'constraints': [models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity'))), name='inventory_reserved_lte_quantity')],
            },
        ),
    ]
