# Generated by Django 5.2.17 on 2026-09-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-created_at'], 'verbose_name': 'Үлдэгдэл', 'verbose_name_plural': 'Агуулахын үлдэгдэл'},
        ),
    ]
