# Generated by Django 5.2.17 on 2026-09-19 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Өөрчилсөн огноо')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Устгагдсан эсэх')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Устгасан огноо')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Нийтийн дугаар (UUID)')),
                ('category', models.CharField(choices=[('LOGIN', 'Нэвтрэлт'), ('ORDER', 'Захиалга'), ('PAYMENT', 'Төлбөр'), ('INVENTORY', 'Агуулах'), ('SETTINGS', 'Тохиргоо'), ('USER', 'Хэрэглэгч')], max_length=20, verbose_name='Ангилал')),
                ('action', models.CharField(max_length=255, verbose_name='Үйлдэл')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP хаяг')),
                ('object_reference', models.CharField(blank=True, max_length=100, verbose_name='Холбогдох баримт')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Хуучин утга')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Шинэ утга')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Сүүлд өөрчилсөн хэрэглэгч')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Аудит лог',
                'verbose_name_plural': 'Аудит логууд',
                'ordering': ['-created_at'],
            },
        ),
    ]
