# Generated by Django 5.2.17 on 2026-09-19 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Өөрчилсөн огноо')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Устгагдсан эсэх')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Устгасан огноо')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Нийтийн дугаар (UUID)')),
                ('notification_type', models.CharField(choices=[('ORDER_APPROVED', 'Захиалга батлагдлаа'), ('ORDER_REJECTED', 'Захиалга татгалзагдлаа'), ('PAYMENT_CONFIRMED', 'Төлбөр батлагдлаа'), ('STOCK_ARRIVED', 'Бараа ирлээ'), ('SHIPPING_STARTED', 'Хүргэлт эхэллээ'), ('COMMISSION_CALCULATED', 'Шимтгэл бодогдлоо')], max_length=30, verbose_name='Мэдэгдлийн төрөл')),
                ('title', models.CharField(max_length=255, verbose_name='Гарчиг')),
                ('message', models.TextField(verbose_name='Агуулга')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Холбогдох баримт')),
                ('is_read', models.BooleanField(default=False, verbose_name='Уншсан эсэх')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Уншсан огноо')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хэрэглэгч')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Хүлээн авагч')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Сүүлд өөрчилсөн хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Мэдэгдэл',
                'verbose_name_plural': 'Мэдэгдлүүд',
                'ordering': ['-created_at'],
            },
        ),
    ]
